[tox]
envlist = py310, ruff, pytest
isolated_build = true

[testenv]
deps = 
    pytest>=6.2.5
    tox>=3.24.4
commands =
    pytest

[testenv:pytest]
deps = pytest>=6.2.5
commands = pytest

[testenv:ruff]
skip_install = true
allowlist_externals = ruff
deps = 
    ruff>=0.9.3
commands =
    ruff check .
