[tox]
envlist = py38, ruff
isolated_build = true

[testenv]
deps = 
    pytest>=6.2.5
    tox>=3.24.4
    flake8>=3.9.2
    black>=21.9b0
    pydocstyle>=6.1.1
    mypy>=0.910
    types-requests>=2.26.1
    isort>=5.10.1
commands =
    pytest
    black --check gluestick/
    flake8 gluestick
    pydocstyle gluestick
    mypy gluestick --exclude='tests'

[testenv:pytest]
envlist = py37, py38, py39
deps = pytest>=6.2.5
commands = pytest

[testenv:format]
deps = 
    black>=21.9b0
    isort>=5.10.1
commands =
    black gluestick/
    isort gluestick

[testenv:ruff]
skip_install = true
allowlist_externals = ruff
deps = 
    ruff>=0.9.3
commands =
    ruff check .

[pydocstyle]
ignore = D105,D203,D213,D210,D413,D411,D401,D100
