### A CI workflow template that runs linting and python testing

name: Test gluestick

on: [push]

jobs:
  # linting:

  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       # Only lint using the primary version used for dev
  #       python-version: ["3.10"]

  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Set up Python ${{ matrix.python-version }}
  #     uses: actions/setup-python@v2
  #     with:
  #       python-version: ${{ matrix.python-version }}
  #   - name: Install dependencies
  #     run: |
  #       pip install .
  #       pip install tox
  #   - name: Run lint command from tox.ini
  #     run: |
  #       tox -e lint

  pytest:

    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install .
        pip install pytest
    - name: Test with pytest
      run: |
        pytest --capture=no
