name: Lint

on:
  pull_request:
    paths:
      - '**/*.py'
      - 'ruff.toml'
      - 'tox.ini'
      - 'pyproject.toml'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install tox
        run: pip install tox

      - name: Run lint
        run: tox
